name: Deno

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: actions/checkout@v2

      - name: Cache Dependencies
        run: deno cache source/index.ts

      - name: Run Linting
        run: deno lint source

      - name: Run Formatting
        run: deno fmt --check source
